_target_ : torchydra_fem.model.components.conv1d_surr.conv1d_surr
activation : 
  _target_ : torch.nn.ReLU
first_dense_layer_out_features: 64
latent_space_dim : 32
conv1DT_latent_dim : 512
dropout_rate : 0.35