_target_ : torchydra_fem.model.components.envir_to_psd.conv1d_surr_nopca.conv1d_surr_nopca
activation : 
  _target_ : torch.nn.ReLU
first_dense_layer_out_features: 64
latent_space_dim : 16
dropout_rate : 0.35