# config.yaml
_target_: src.models.conv1D_surr.Conv1D_Surr

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 64
  lin2_size: 128
  lin3_size: 64
  output_size: 10


# Environmental variables
ENVIR_VARIABLES: [dp, tp, hs, mag10, theta10]

# Neuron variables
NEURON_VARIABLES: 
    - NeurNode1ALxt_psd
    - NeurNode1ALyt_psd
    - NeurNode1ALzt_psd
    - NeurNode3ALxt_psd
    - NeurNode3ALyt_psd
    - NeurNode3ALzt_psd

# Dataset path
dataset: ./data/training_netcdf_databases/reference_dataset_Zefyros_windeurope.nc

# Environmental direction dictionary
envir_direction_dict:
  mag10: theta10
  hs: dp

# Environmental bin
environmental_bin:
  hs: 1
  tp: 2
  dp: 45
  mag10: 2
  theta10: 45

# Number of test samples and clusters
Test_nb: 40
cluster: 3

# Output folders
unscaled_netcdf_training_dataset: ./data/training_netcdf_databases

# PCA number of components
n_component: 32

# Frequency range for training
cut_low_frequency: 0.02857142857

# Model parameters
model_name: model_1DConvT
model_version: v1

# Training parameters
epochs: 100
batch_size: 32
loss: mse
learn_rate: 0.001
dropout_rate: 0.2
