# @package _global_

defaults:
  - _self_
  - hydra: default.yaml
  - extras: default.yaml
  - paths: ins2tension_monabiop.yaml


task_name: "infer_time_series_to_stats"
tags: ["dev"]

# passing checkpoint path is necessary for evaluation
experiment_folder: outputs\Monabiop\time_series_to_stats\conv1d\runs\2023-10-20_16-28-22


# location of envir files for inference and for storing the model inference results. 
save_path: ${paths.data_dir}/inferences/${task_name}
