# config.yaml file for hydra
# This is the default config file for hydra
# It is used to configure the training and testing of the model and the dataset

_target_: config_schema.Preprocessing

defaults:
  - _self_
  - hydra: default.yaml
  - preprocessing: default.yaml
  - model : surrogate_module.yaml
  - trainer: cpu.yaml
  - callbacks : default.yaml
  - logger: tensorboard.yaml
  - data : surrogate.yaml
  - hparams_search : mnist_optuna.yaml
  - override hydra/sweeper: optuna

model_net :  
  _target_ : model.components.conv1D_surr.conv1D_surr
  dropout_rate : 0.5
  activation : 
    _target_ : torch.nn.ReLU
  first_dense_layer_out_features: 128
  latent_space_dim : 16
  conv1DT_latent_dim : 512

  

task_name: "train_surrogate"        # task name, determines output directory path

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# compile model for faster training with pytorch 2.0
compile: False

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: null


