model:
  _target_: model.surrogate_module.SurrogateModule
  optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.001
    weight_decay: 0.0
  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: true
    mode: min
    factor: 0.1
    patience: 10
model/params/total: 728854
model/params/trainable: 728854
model/params/non_trainable: 0
data:
  _target_: data.surrogate.SurrogateDataModule
  batch_size: 32
  num_workers: 0
  pin_memory: false
trainer:
  _target_: lightning.pytorch.trainer.Trainer
  default_root_dir: ./
  min_epochs: 1
  max_epochs: 2
  accelerator: cpu
  devices: 1
  check_val_every_n_epoch: 1
  deterministic: false
callbacks:
  model_checkpoint:
    _target_: lightning.pytorch.callbacks.ModelCheckpoint
    dirpath: ./checkpoints
    filename: epoch_{epoch:03d}
    monitor: train/loss
    verbose: false
    save_last: true
    save_top_k: 1
    mode: max
    auto_insert_metric_name: false
    save_weights_only: false
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null
  early_stopping:
    _target_: lightning.pytorch.callbacks.EarlyStopping
    monitor: train/loss
    min_delta: 0.0
    patience: 100
    verbose: false
    mode: max
    strict: true
    check_finite: true
    stopping_threshold: null
    divergence_threshold: null
    check_on_train_epoch_end: null
  model_summary:
    _target_: lightning.pytorch.callbacks.RichModelSummary
    max_depth: -1
  rich_progress_bar:
    _target_: lightning.pytorch.callbacks.RichProgressBar
extras: null
task_name: train_surrogate
tags:
- dev
ckpt_path: null
seed: null
